#!/usr/bin/env bash
set -euo pipefail

# Linux/macOS setup helper:
# - installs build dependencies (apt/brew)
# - optionally downloads Android SDK cmdline-tools + NDK
# - generates ./scripts/android-env.sh you can source before building

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
HELPER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

NDK_VERSION_DEFAULT="26.2.11394342"

say() { echo "[*] $*"; }
warn() { echo "[!] $*" >&2; }
fail() { echo "ERROR: $*" >&2; exit 1; }

is_tty() {
  [[ -t 1 ]]
}

run_with_spinner() {
  # Use for commands that don't show progress (e.g. unzip -q).
  # If stdout is not a TTY (CI logs), just run the command normally.
  local label="$1"; shift

  if ! is_tty; then
    say "$label"
    "$@"
    return
  fi

  say "$label"
  "$@" &
  local pid=$!

  local spin='|/-\\'
  local i=0
  while kill -0 "$pid" >/dev/null 2>&1; do
    i=$(( (i + 1) % 4 ))
    printf "\r[*] %s... %s" "$label" "${spin:$i:1}"
    sleep 0.12
  done
  wait "$pid"
  printf "\r[*] %s... done\n" "$label"
}

os_name() {
  case "$(uname -s)" in
    Linux) echo linux;;
    Darwin) echo mac;;
    *) echo other;;
  esac
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

prompt() {
  local msg="$1"
  local def="${2:-}"
  local input=""
  if [[ -n "$def" ]]; then
    read -r -p "$msg [$def]: " input || true
    echo "${input:-$def}"
  else
    read -r -p "$msg: " input || true
    echo "$input"
  fi
}

install_deps_linux() {
  if ! command -v apt-get >/dev/null 2>&1; then
    warn "apt-get not found; skipping dependency install."
    return 0
  fi

  local sudo_cmd=""
  if [[ $EUID -ne 0 ]]; then
    if command -v sudo >/dev/null 2>&1; then
      sudo_cmd="sudo"
    else
      warn "Not root and sudo not found; cannot install packages automatically."
      return 0
    fi
  fi

  say "Installing dependencies via apt-get (may prompt for password)"
  $sudo_cmd apt-get update
  $sudo_cmd apt-get install -y --no-install-recommends \
    ca-certificates curl unzip git make perl patch \
    openjdk-17-jre-headless \
    nasm pkg-config
}

install_deps_macos() {
  if ! command -v brew >/dev/null 2>&1; then
    warn "Homebrew not found; skipping dependency install."
    warn "Install Homebrew from https://brew.sh/ then re-run this script if you want auto setup."
    return 0
  fi

  say "Installing dependencies via brew"
  brew update >/dev/null 2>&1 || true
  brew install git make perl patch nasm pkg-config curl unzip || true
  brew install --cask temurin || true
}

sdk_tools_zip_url() {
  # Update if Google bumps the cmdline tools version.
  local os
  os="$(os_name)"
  case "$os" in
    linux) echo "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip";;
    mac) echo "https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip";;
    *) fail "Unsupported OS for auto SDK install: $(uname -s)";;
  esac
}

ensure_cmdline_tools() {
  local sdk_root="$1"

  mkdir -p "$sdk_root/cmdline-tools"
  if [[ -x "$sdk_root/cmdline-tools/latest/bin/sdkmanager" ]]; then
    return 0
  fi

  need_cmd curl
  need_cmd unzip

  local url zip tmp
  url="$(sdk_tools_zip_url)"
  zip="$sdk_root/cmdline-tools/_cmdline-tools.zip"
  tmp="$sdk_root/cmdline-tools/_tmp"

  say "Downloading Android cmdline-tools"
  rm -rf "$tmp" || true
  mkdir -p "$tmp"
  # Show a progress bar (works well on both Linux and macOS curl).
  curl -fL --progress-bar -o "$zip" "$url"

  run_with_spinner "Extracting cmdline-tools" unzip -q "$zip" -d "$tmp"

  # The zip contains cmdline-tools/; move into cmdline-tools/latest
  rm -rf "$sdk_root/cmdline-tools/latest" || true
  mkdir -p "$sdk_root/cmdline-tools"
  mv "$tmp/cmdline-tools" "$sdk_root/cmdline-tools/latest"

  rm -rf "$tmp" || true
  rm -f "$zip" || true
}

write_env_file() {
  local sdk_root="$1"
  local ndk_version="$2"
  local env_file="$SCRIPT_DIR/android-env.sh"

  cat >"$env_file" <<EOF
# Generated by ./scripts/setup-unix.sh
export ANDROID_SDK_ROOT="${sdk_root}"
export ANDROID_NDK="${sdk_root}/ndk/${ndk_version}"
export PATH="${sdk_root}/cmdline-tools/latest/bin:${sdk_root}/platform-tools:\$PATH"
EOF

  chmod 0644 "$env_file" || true
  say "Wrote environment file: $env_file"
  say "Next: source it with: source ./scripts/android-env.sh"
}

main() {
  local os
  os="$(os_name)"
  [[ "$os" != "other" ]] || fail "This setup script only supports Linux/macOS."

  say "Linux/macOS setup for ijkplayer-16kb-helper"

  local do_deps
  do_deps="$(prompt "Install build dependencies (apt/brew)?" "Y")"
  if [[ "${do_deps}" =~ ^[Yy]$ ]]; then
    if [[ "$os" == "linux" ]]; then
      install_deps_linux
    else
      install_deps_macos
    fi
  fi

  # If NDK already set, offer to just write env file.
  if [[ -n "${ANDROID_NDK:-}" || -n "${ANDROID_NDK_HOME:-}" ]]; then
    say "ANDROID_NDK is already set; skipping SDK/NDK install."
    exit 0
  fi

  local choice
  echo ""
  echo "Android SDK/NDK setup (required for local Linux/macOS builds):"
  echo "  1) Download + install into \$HOME/Android/Sdk (recommended)"
  echo "  2) Download + install into \$HOME/.android-sdk"
  echo "  3) Download + install into <helper>/.android-sdk (portable, not recommended for git)"
  echo "  4) I will set ANDROID_NDK / ANDROID_SDK_ROOT manually (try again later)"
  choice="$(prompt "Choice" "1")"

  local sdk_root
  case "$choice" in
    1) sdk_root="$HOME/Android/Sdk";;
    2) sdk_root="$HOME/.android-sdk";;
    3) sdk_root="$HELPER_DIR/.android-sdk";;
    4) fail "Set ANDROID_NDK (or ANDROID_NDK_HOME) and re-run ./scripts/run.sh";;
    *) fail "Invalid choice";;
  esac

  local ndk_version
  ndk_version="$(prompt "NDK version" "$NDK_VERSION_DEFAULT")"

  ensure_cmdline_tools "$sdk_root"

  export ANDROID_SDK_ROOT="$sdk_root"
  export PATH="$sdk_root/cmdline-tools/latest/bin:$sdk_root/platform-tools:$PATH"

  need_cmd sdkmanager

  say "Accepting Android SDK licenses"
  # Leave output enabled so users can see progress.
  yes | sdkmanager --sdk_root="$sdk_root" --licenses || true

  say "Installing platform-tools + NDK ($ndk_version)"
  sdkmanager --sdk_root="$sdk_root" \
    "platform-tools" \
    "ndk;${ndk_version}"

  if [[ ! -d "$sdk_root/ndk/$ndk_version" ]]; then
    fail "NDK install did not produce expected folder: $sdk_root/ndk/$ndk_version"
  fi

  write_env_file "$sdk_root" "$ndk_version"

  echo ""
  say "Setup complete."
  echo "Local build next steps:" 
  echo "  source ./scripts/android-env.sh"
  echo "  bash ./scripts/run.sh"
}

main "$@"
